on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: cascap.azurecr.io
        username: ${{ secrets.acr_cascap_username }}
        password: ${{ secrets.acr_cascap_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/ubuntu19.04-and-dotnetcore3.0" -f  "ubuntu19.04-and-dotnetcore3.0/Dockerfile" -t cascap.azurecr.io/deltron9:${{ github.sha }}
        docker push cascap.azurecr.io/deltron9:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_deltron9_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep deltron94927 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace deltron94927`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: deltron94927
        container-registry-url: cascap.azurecr.io
        container-registry-username: ${{ secrets.acr_cascap_username }}
        container-registry-password: ${{ secrets.acr_cascap_password }}
        secret-name: deltron9dockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: deltron94927
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          cascap.azurecr.io/deltron9:${{ github.sha }}
        imagepullsecrets: |
          deltron9dockerauth